POST http://127.0.0.1:8000/login
content-type:application/json

{"username":"johitj","password":"pass12345"}


###

POST http://127.0.0.1:8000/signup
content-type:application/json



{"username":"johitj","password":"pass12345","email":"jonas@gmail.com"}


###

GET http://127.0.0.1:8000/test
content-type:application/json

{}


