# Generated by Django 5.1.1 on 2024-11-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
